import type { Metadata } from "next";
import { Mulish, Poppins } from "next/font/google";
import "./globals.css";

export const poppins = Poppins({
  weight: ["500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const mulish = Mulish({
  weight: ["400", "500", "600", "700", "900", "1000"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>{children}</body>
    </html>
  );
}
